needs_setup: true
groups:
  - client-a
public_services:
  - service: nginx
    port: 80
domain: simple_nginx.ddev.site
time_to_live: !Days 7
basic_auth: null
disallow_robots: true
middlewares:
  - rate-limit
  - cors-headers
environment:
  FOO: BAR
  FOOX: hjfaklsjghfkljhsaflkgjhasflgkhjasflkgjhasfklgjhasklfghjsalkjghasflgkjhasfklgjhfsgalkfgjhaslkfgjhaslfkgjhasfglkjahsfglksajfghaskfgjhasfglkjhaslkjghaslkfgjhasflgkjhasfglkjhagsflkj
  FOOX_AUTH: hjfaklsjghfkljhsaflkgjhasflgkhjasflkgjhasfklgjhasklfghjsalkjghasflgkjhasfklgjhfsgalkfgjhaslkfgjhaslfkgjhasfglkjahsfglksajfghaskfgjhasfglkjhaslkjghaslkfgjhasflgkjhasfglkjhagsflkj
registry: factorial
app_blueprint: nginx-lagoon
notify:
  - Log
  - !Mattermost
    service_id: chat.factorial.io
    channel: test-test-test
  - !Webhook
    service_id: webhook-test
