before_script:
  - "cd ${CI_PROJECT_DIR}"
  - "eval `ssh-agent`"
  - "echo $SSH_AGENT_PID > SSH_AGENT_PID_FILE"
  - "ssh-add ~/.ssh/bot.id_rsa"

stages:
  - init
  - lint
  - test
  - setup
  - backup
  - deploy

variables:
  TAG_VERSION_C: $CI_COMMIT_REF_SLUG

# Linting Tasks

lint:docker-images:
  stage: lint
  needs: []
  extends: .lint:docker-images

lint:scotty:
  stage: lint
  needs: []
  extends: .lint:scotty

test:scotty:
  stage: test
  needs: []
  extends: .test:scotty

build:scotty:
  stage: setup
  needs: [test:scotty, lint:scotty]
  variables:
    TAG_VERSION_C: $CI_COMMIT_REF_SLUG
  extends: .build:scotty

# Deploy Options

## Dev individual
deploy-testbed:
  needs: [build:scotty]
  stage: deploy
  variables:
    TAG_VERSION_C: $CI_COMMIT_REF_SLUG
    PHAB_CONFIG_NAME: $DEV_PHAB_CONFIG_NAME
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "xxx_dev"'
  extends: .deploy

## Stage individual
deploy-stage:
  needs: [build:scotty]
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main"'
  extends: .deploy-docker-compose

include:
  - remote: "https://config.factorial.io/gitlab-ci/defaults.yml"
  - local: ".gitlab-ci/components/init.yml"
  - local: ".gitlab-ci/components/build.yml"
  - local: ".gitlab-ci/components/lint.yml"
  - local: ".gitlab-ci/components/test.yml"
  - local: ".gitlab-ci/components/backup.yml"
  - local: ".gitlab-ci/components/deploy.yml"
