before_script:
  - "cd ${CI_PROJECT_DIR}"
  - "eval `ssh-agent`"
  - "echo $SSH_AGENT_PID > SSH_AGENT_PID_FILE"
  - "ssh-add ~/.ssh/bot.id_rsa"

stages:
  - init
  - lint
  - test
  - setup
  - backup
  - deploy
  - sync

variables:
  TAG_VERSION_C: $CI_COMMIT_TAG

# Stage: setup

lint:docker:
  stage: lint
  needs: []
  extends: .lint:docker

lint:scotty:
  stage: lint
  needs: []
  extends: .lint:scotty

test:scotty:
  stage: test
  needs: []
  extends: .test:scotty

build:scotty:
  stage: setup
  needs: [test:scotty, lint:scotty, lint:docker]
  variables:
    TAG_VERSION_C: $CI_COMMIT_REF_SLUG
  extends: .build:scotty

# Deploy Options

## Prod individual

backup-prod-db:
  stage: backup
  needs: []
  variables:
    PHAB_CONFIG_NAME: www.factorial.io
  extends: .backup-db-only

include:
  - remote: "https://config.factorial.io/gitlab-ci/defaults.yml"
  - local: ".gitlab-ci/components/init.yml"
  - local: ".gitlab-ci/components/build.yml"
  - local: ".gitlab-ci/components/lint.yml"
  - local: ".gitlab-ci/components/test.yml"
  - local: ".gitlab-ci/components/backup.yml"
  - local: ".gitlab-ci/components/deploy.yml"

deploy-prod:
  needs: [create-frontend-job-tag, create-backend-job-tag, backup-prod-db]
  stage: deploy
  variables:
    TAG_VERSION_C: $CI_COMMIT_TAG
  extends: .deploy:live
#copy-db-to-stage:
#  stage: sync
#  needs: [deploy-prod]
#  variables:
#    COPY_TO: main.factorialwebsite.oterma.factorial.io
#    COPY_FROM: www.factorial.io
#  extends: .copy-db
