#ddev-generated
services:
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.ddev.site`)"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
