services:
  yafbds:
    image: registry.factorial.io/administration/yafbds/yafbds:main
    volumes:
      - ..:/app/apps
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RUST_LOG: info
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yafbds.rule=Host(`yafbds.ddev.site`)"
      - "traefik.http.services.yafbds.loadbalancer.server.port=21342"
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    environment:
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.ddev.site`)"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
