.deploy-docker-compose:
  before_script: []
  after_script: []
  script:
    - docker login $CI_REGISTRY -u $CI_DEPLOY_USER -p "$CI_DEPLOY_PASSWORD"
    - cd /opt/containers/yafbds && docker compose pull && docker compose rm -f -s && docker compose up -d
  tags:
    - yafbds-testbed
