# Authorization configuration without hardcoded bearer tokens
# Bearer tokens should be provided via environment variables for security

scopes:
  qa:
    description: QA Environment
    created_at: '2024-01-01T00:00:00Z'
  client-a:
    description: Client A Applications
    created_at: '2024-01-01T00:00:00Z'
  client-b:
    description: Client B Applications
    created_at: '2024-01-01T00:00:00Z'
  default:
    description: Default scope for unassigned apps
    created_at: '2024-01-01T00:00:00Z'

roles:
  admin:
    permissions:
    - '*'
    description: Full system access (all permissions)
  developer:
    permissions:
    - view
    - manage
    - shell
    - logs
    - create
    description: Developer access - all except destroy
  operator:
    permissions:
    - view
    - manage
    - logs
    description: Operations team - no shell or destroy
  viewer:
    permissions:
    - view
    description: Read-only access

# Token assignments are loaded from environment variables:
# SCOTTY_ADMIN_TOKENS="secure-admin-token-123,backup-admin-456"
# SCOTTY_TOKEN_ASSIGNMENTS='[{"token":"ci-token","role":"developer","scopes":["qa"]}]'
assignments:
  # Default assignment: everyone gets viewer access to default scope
  '*':
  - role: viewer
    scopes:
    - default

# App to scope mappings (managed automatically by Scotty)
apps: {}