{
 "title": "Scotty - HTTP Server",
 "tags": [ "scotty" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "scotty_http_requests_active", "legendFormat": "Active Requests" }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(scotty_http_requests_total[1m])",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(scotty_http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "Request Duration p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(scotty_http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "Request Duration p95"
    },
    {
     "expr": "histogram_quantile(0.50, rate(scotty_http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "Request Duration p50"
    }
   ]
  }
 ]
}