# Development mode configuration
# No authentication required - direct access to Scotty

api:
  bind_address: "0.0.0.0:3000"
  auth_mode: "dev"
  dev_user_email: "developer@localhost"  
  dev_user_name: "Local Developer"