services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`simple-nginx.ddev.site`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

    image: nginx:$BRANCH
    volumes:
      - ./html:/usr/share/nginx/html
