apps:
  blueprints:
    nginx-lagoon:
      name: "NGINX using lagoon base images"
      description: "A simple NGINX container using lagoon base images"
      public_services:
        nginx: 80
      actions:
        post_create:
          nginx:
            - echo "Hello, World from post_create"
            - env
        post_rebuild:
          nginx:
            - echo "Hello, World from post_rebuild"
            - env
        post_run:
          nginx:
            - echo "Hello, World from post_run"
            - env
    drupal-lagoon:
      name: "Drupal using lagoon base images"
      description: "A simple Drupal application using lagoon base images (cli, php, nginx)"
      public_services:
        nginx: 8080
      actions:
        post_create:
          cli:
            - drush deploy
        post_rebuild:
          cli:
            - drush deploy
        post_run:
          cli:
            - drush uli
