api:
  bind_address: "127.0.0.1:21342"
telemetry: Traces
apps:
  domain_suffix: "ddev.site"
  use_tls: false
  root_folder: "./apps" # Path to the folder where the apps are stored
docker: local # local, socket or http, see bollard docs
load_balancer_type: HaproxyConfig #HaproxyConfig or Traefik
traefik:
  use_tls: false
haproxy:
  use_tls: false
