api:
  bind_address: "127.0.0.1:21342"
  access_token: hello-world
telemetry: None
apps:
  domain_suffix: "ddev.site"
  use_tls: false
  root_folder: "./apps" # Path to the folder where the apps are stored
docker:
  connection: local # local, socket or http, see bollard docs
load_balancer_type: Traefik #HaproxyConfig or Traefik
traefik:
  use_tls: false
haproxy:
  use_tls: false
notification_services:
  chat.factorial.io:
    type: mattermost
    host: https://chat.factorial.io
    hook_id: xxx # Override with SCOTTY__NOTIFICATION_SERVICES__CHAT_FACTORIAL_IO__HOOK_ID
  webhook-test:
    type: webhook
    method: post
    url: https://wh66e463ada4ac505d47.free.beeceptor.com
