services:
  web:
    environment:
      HELLO_WORLD: $HELLO_WORLD
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`invalid-site.ddev.site`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
