apps:
    blueprints:
        drupal-lagoon:
            name: "Drupal using lagoon base images"
            description: "A simple Drupal application using lagoon base images (cli, php, nginx)"
            required_services:
                - cli
                - php
                - nginx
            public_services:
                nginx: 8080
            actions:
                post_create:
                    description: "Run drush deploy after the application is created"
                    commands:
                        cli:
                            - drush deploy --uri=$SCOTTY__PUBLIC_URL__NGINX
                post_rebuild:
                    description: "Run drush deploy after the application is rebuilt"
                    commands:
                        cli:
                            - drush deploy --uri=$SCOTTY__PUBLIC_URL__NGINX
                post_run:
                    description: "Generate a one-time login link, after the application started successfully"
                    commands:
                        cli:
                            - drush uli --uri=$SCOTTY__PUBLIC_URL__NGINX
                drush:uli:
                    description: "Generate a one-time login link"
                    commands:
                        cli:
                            - drush uli --uri=$SCOTTY__PUBLIC_URL__NGINX
                drush:deploy:
                    description: "Run drush deploy"
                    commands:
                        cli:
                            - drush deploy --uri=$SCOTTY__PUBLIC_URL__NGINX
