apps:
    blueprints:
        drupal-lagoon:
            name: "Drupal using lagoon base images"
            description: "A simple Drupal application using lagoon base images (cli, php, nginx)"
            required_services:
                - cli
                - php
                - nginx
            public_services:
                nginx: 8080
            actions:
                post_create:
                    cli:
                        - echo "Running drush deploy ..."
                        - drush deploy --uri=$SCOTTY__PUBLIC_URL__NGINX
                post_rebuild:
                    cli:
                        - echo "Running drush deploy ..."
                        - drush deploy --uri=$SCOTTY__PUBLIC_URL__NGINX
                post_run:
                    cli:
                        - echo "Running drush uli ..."
                        - drush uli --uri=$SCOTTY__PUBLIC_URL__NGINX
