apps:
    blueprints:
        nginx-lagoon:
            name: "NGINX using lagoon base images"
            description: "A simple NGINX container using lagoon base images"
            required_services:
                - nginx
            public_services:
                nginx: 80
            actions:
                post_create:
                    description: "Initialize the application after creation"
                    commands:
                        nginx:
                            - echo "Hello, World from post_create"
                            - env
                post_rebuild:
                    description: "Setup the application after rebuilding"
                    commands:
                        nginx:
                            - echo "Hello, World from post_rebuild"
                            - env
                post_run:
                    description: "Configure the application after starting"
                    commands:
                        nginx:
                            - echo "Hello, World from post_run"
                            - env
                status:
                    description: "Display NGINX status information and running processes"
                    commands:
                        nginx:
                            - nginx -v
