public_services:
- service: nginx
  port: 80
  domains: []
domain: test-env.ddev.site
time_to_live: !Days 7
destroy_on_ttl: false
basic_auth: null
disallow_robots: true
environment: {}
registry: null
app_blueprint: null
notify: []
middlewares:
- test-middleware
