# This is a basic workflow to help you get started with Actions

name: Build and deploy documentation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [docs]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Deploy
        uses: stmh/vuepress-github-actions-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.PAT }}
          BUILD_DIR: _site
          BUILD_SCRIPT: cd docs && export FDOCS_HOST=https://scotty.factorial.io && yarn install --ignore-engines && yarn run docs:build
          PAGES_CNAME: scotty.factorial.io
