name: Release and Publish

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          changelog: CHANGELOG.md
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          # Universal macOS binary is supported as universal-apple-darwin.
          - target: universal-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: scottyctl
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

  homebrew:
    name: Bump Homebrew formula
    needs: upload-assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: extract-version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          # GitHub token, required for authentication
          # Using a Personal Access Token with repo scope to allow pushing to another repository
          token: ${{ secrets.PAT }}

          # Optional: Name of the tap repository without the homebrew- prefix
          # For example, for a repo homebrew-tap, this would be "tap"
          # Default: core (homebrew/homebrew-core)
          # You need to create this repository first!
          tap: factorial-io/scottyctl-tap

          # Required: Formula name
          formula: scottyctl

          # Optional: Define the formula path in the tap repo
          # Default: Formula/#{formula}.rb
          formula_filepath: scottyctl.rb

          # Optional: Specify a tag name or SHA to use
          # Default: latest release
          tag: v${{ steps.extract-version.outputs.VERSION }}

          # Optional: Revision to use (can be a SHA or a tag name or a release version)
          # If not specified, the action will use the tag from the event
          revision: v${{ steps.extract-version.outputs.VERSION }}